### ISSUE TITLE
Mod does not display anything 

### ISSUE THREAD

**Issue by Syfooo** [cotrin8672/ItemIndicator#9]
Log reads  [main/WARN] [mixin/]: Reference map 'inventoryessentials.refmap.json' for inventoryessentials.mixins.json could not be read. If this is a development environment you can ignore this message

**Comment by cotrin8672** [comment]
This information alone does not identify the cause. At a minimum, please describe Minecraft, the mod that causes the problem in conjunction with it, and the version of the mod.
